#https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml
#Cypress runs on GH Actions using Ubuntu (20 and 22), Windows, and macOS without additional OS dependencies necessary.
name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        # normally you would write
        uses: cypress-io/github-action@v6
        # uses: ./
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
        #   working-directory: examples/basic
          spec: cypress/e2e/github_actions_demo/**/*
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
        #   build: npx cypress info

  basic-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        # uses: ./
        uses: cypress-io/github-action@v6
        with:
        #   working-directory: examples/basic
          spec: cypress/e2e/github_actions_demo/**/*
        #   build: npx cypress info

  basic-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        # uses: ./
        uses: cypress-io/github-action@v6
        with:
        #   working-directory: examples/basic
          spec: cypress/e2e/github_actions_demo/**/*
        #   build: npx cypress info

#   basic-on-mac:
#     runs-on: macos-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Cypress tests
#         uses: ./
#         with:
#           working-directory: examples/basic
#           spec: cypress/e2e/github_actions_demo/**/*
#           build: npx cypress info

#   # skips the binary installation
#   # shows that the job should not fail
#   # https://github.com/cypress-io/github-action/issues/327
#   basic-without-binary-install:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Cypress tests
#         uses: ./
#         with:
#           working-directory: examples/basic
#           spec: cypress/e2e/github_actions_demo/**/*
#           # since we do not install Cypress
#           # we should not attempt to run tests
#           runTests: false
#         env:
#           # skip the binary install
#           CYPRESS_INSTALL_BINARY: 0